name: CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - uses: nrwl/nx-set-shas@v5

      - name: Install deps
        run: npm ci

      - name: Lint affected
        run: npx nx affected -t lint

      - name: Build affected
        run: npx nx affected -t build
